## Defaults localhost. Host for RabbitMQ
#rabbitmq_host: 
## Defaults 5672. Port for RabbitMQ
#rabbitmq_port: 
## Defaults 0. Connect using SSL/TLS
#rabbitmq_ssl: 
## Optional. Defaults None. Path to client private key for SSL/TLS
#rabbitmq_ssl_key: 
## Optional. Defaults None. Path to client certificate for SSL/TLS
#rabbitmq_ssl_cert: 
## Optional. Defaults None. Path to CA certificate for SSL/TLS
#rabbitmq_ssl_cacert: 
## Default /
#rabbitmq_vhost: 
## Default guest
#rabbitmq_username: 
## Default guest
#rabbitmq_password: 
## Default logstash-queue.
#rabbitmq_queue: 
## Default 0.
#rabbitmq_queue_durable: 
## Default direct.
#rabbitmq_exchange_type: 
## Default 0.
#rabbitmq_exchange_durable: 
## Default logstash-key.
#rabbitmq_key: 
## Default logstash-exchange.
#rabbitmq_exchange: 
## Default 1. The timeout in seconds for the connection to the RabbitMQ broker
#rabbitmq_timeout: 
## Default 1. Message deliveryMode. 1: non persistent 2: persistent
#rabbitmq_delivery_mode: 
